# Generated by Django 4.2.5 on 2023-09-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jam',
            new_name='Item',
        ),
    ]
